<h1><?= e($o['order_number']) ?></h1>
<div class="agrid"><div class="card"><h3>Items</h3><?php foreach ($items as $i): ?><div class="srow"><span><?= e($i['product_name']) ?> × <?= (int)$i['quantity'] ?></span><b><?= money((float)$i['line_total']) ?></b></div><?php endforeach; ?><div class="srow tot"><span>Total</span><b><?= money((float)$o['total']) ?></b></div>
<p><?= e($o['recipient']) ?> · <?= e($o['phone']) ?><br><?= e($o['address_line']) ?>, <?= e($o['city']) ?> <?= e($o['postcode']) ?></p></div>
<div class="card"><h3>Status: <?= e($o['status']) ?></h3><form method="post" action="/admin/orders/<?= (int)$o['id'] ?>/status" class="row"><?= csrf_field() ?><select name="status"><?php foreach (['pending','confirmed','processing','packed','out_for_delivery','delivered','cancelled'] as $s): ?><option <?= $o['status'] === $s ? 'selected' : '' ?>><?= $s ?></option><?php endforeach; ?></select><button class="btn">Update</button></form></div>
<div class="card"><h3>Payment: <?= e($o['payment_method']) ?> (<?= e($pay['status'] ?? $o['payment_status']) ?>)</h3>
<?php if ($o['payment_method'] === 'cod' && (int)$o['needs_change']): ?><p>Customer bayar dengan <b><?= money((float)$o['cash_tendered']) ?></b> — sediakan duit kecil <?= money(max(0, (float)$o['cash_tendered'] - (float)$o['total'])) ?></p><?php endif; ?>
<?php if (!empty($o['latitude']) && !empty($o['longitude'])): ?><p>Pin: <?= e($o['latitude']) ?>, <?= e($o['longitude']) ?> <a target="_blank" rel="noopener" href="https://www.google.com/maps?q=<?= e($o['latitude']) ?>,<?= e($o['longitude']) ?>">Buka di Google Maps →</a></p><?php endif; ?>
<?php if (($pay['status'] ?? '') === 'claimed'): ?><div class="row"><form method="post" action="/admin/orders/<?= (int)$o['id'] ?>/pay-confirm"><?= csrf_field() ?><button class="btn">Sahkan Dah Bayar</button></form><form method="post" action="/admin/orders/<?= (int)$o['id'] ?>/pay-reject"><?= csrf_field() ?><button class="btn ghost">Belum / Tolak</button></form></div>
<?php endif; ?></div></div>
