USE webgroceries;
INSERT INTO users (name,email,password_hash,phone,role) VALUES
('Store Admin','admin@webgroceries.test','$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi','012-3456789','admin'),
('Aina Rahman','aina@test.test','$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi','012-1112223','customer');
-- password for both: "password"

INSERT INTO categories (name,slug,description,image,status) VALUES
('Fresh Produce','fresh-produce','Seasonal fruits and vegetables, picked daily.','cat-produce.jpg','active'),
('Meat & Seafood','meat-seafood','Fresh chicken, beef and seafood.','cat-meat.jpg','active'),
('Dairy & Eggs','dairy','Milk, cheese, yoghurt and farm eggs.','cat-dairy.jpg','active'),
('Beverages','beverages','Juices, coffee, tea and soft drinks.','cat-bev.jpg','active'),
('Snacks','snacks','Chips, biscuits, nuts and treats.','cat-snacks.jpg','active'),
('Frozen Food','frozen-food','Frozen meals, desserts and staples.','cat-frozen.jpg','active'),
('Pantry','pantry','Rice, oil, flour, canned goods and spices.','cat-pantry.jpg','active'),
('Household','household','Cleaning and home essentials.','cat-home.jpg','active'),
('Personal Care','personal-care','Soap, shampoo and everyday care.','cat-care.jpg','active');

INSERT INTO products (category_id,brand,name,slug,description,price,discount_price,stock_quantity,unit,image,status,is_featured,is_bestseller) VALUES
(1,'Cameron Highlands','Fresh Strawberries 250g','fresh-strawberries-250g','Sweet highland strawberries, chilled on arrival.',12.90,9.90,120,'pack','/assets/images/products/fresh-strawberries-250g.jpg','active',1,1),
(1,'Local Farm','Bananas 1kg','bananas-1kg','Cavendish bananas, energy-packed and ripe.',6.50,NULL,200,'kg','/assets/images/products/bananas-1kg.jpg','active',1,1),
(1,'Organic Select','Spinach 400g','spinach-400g','Crisp organic spinach, washed and ready.',5.20,4.20,90,'pack','/assets/images/products/spinach-400g.jpg','active',0,0),
(1,'Fresh Daily','Red Apples 1kg','red-apples-1kg','Juicy fuji apples, crunchy and sweet.',11.90,NULL,150,'kg','/assets/images/products/red-apples-1kg.jpg','active',1,0),
(1,'Veggie Box','Cherry Tomatoes 500g','cherry-tomatoes-500g','Vine-ripened cherry tomatoes.',7.80,6.50,110,'pack','/assets/images/products/cherry-tomatoes-500g.jpg','active',0,1),
(2,'Farm Fresh','Whole Chicken 1.2kg','whole-chicken-12kg','Antibiotic-free whole chicken, cleaned.',19.90,17.90,60,'bird','/assets/images/products/whole-chicken-12kg.jpg','active',1,1),
(2,'Premium Beef','Sirloin Steak 500g','sirloin-steak-500g','Chilled Australian sirloin, tender cut.',42.00,NULL,35,'pack','/assets/images/products/sirloin-steak-500g.jpg','active',1,0),
(2,'Ocean Catch','Salmon Fillet 300g','salmon-fillet-300g','Norwegian salmon fillet, sushi-grade.',29.90,26.90,40,'pack','/assets/images/products/salmon-fillet-300g.jpg','active',1,1),
(2,'Ocean Catch','Tiger Prawns 500g','tiger-prawns-500g','Large tiger prawns, deveined.',24.50,NULL,55,'pack','/assets/images/products/tiger-prawns-500g.jpg','active',0,0),
(3,'Farm Milk Co','Fresh Milk 1L','fresh-milk-1l','Pasteurised fresh milk, high calcium.',7.20,6.40,180,'bottle','/assets/images/products/fresh-milk-1l.jpg','active',1,1),
(3,'Farm Milk Co','Cheddar Cheese 250g','cheddar-cheese-250g','Aged cheddar block, rich flavour.',14.90,NULL,70,'block','/assets/images/products/cheddar-cheese-250g.jpg','active',0,0),
(3,'Yogood','Greek Yoghurt 500g','greek-yoghurt-500g','Thick protein-rich greek yoghurt.',11.50,9.90,85,'tub','/assets/images/products/greek-yoghurt-500g.jpg','active',0,1),
(3,'Happy Hen','Free-Range Eggs 10s','free-range-eggs-10s','Omega-enriched free-range eggs.',13.90,NULL,140,'tray','/assets/images/products/free-range-eggs-10s.jpg','active',1,1),
(4,'Tropica','Orange Juice 1L','orange-juice-1l','100% squeezed orange, no added sugar.',9.80,8.50,130,'bottle','/assets/images/products/orange-juice-1l.jpg','active',0,1),
(4,'Kopi Kita','Ground Coffee 250g','ground-coffee-250g','Medium-roast arabica, locally roasted.',22.90,NULL,65,'pack','/assets/images/products/ground-coffee-250g.jpg','active',1,0),
(4,'Teh Wangi','Jasmine Green Tea 50s','jasmine-green-tea-50s','Fragrant jasmine green tea bags.',12.50,10.90,100,'box','/assets/images/products/jasmine-green-tea-50s.jpg','active',0,0),
(4,'FizzPop','Sparkling Water 6x500ml','sparkling-water-6pack','Zero-sugar sparkling mineral water.',13.20,NULL,160,'pack','/assets/images/products/sparkling-water-6pack.jpg','active',0,0),
(5,'Crunchy','Sea Salt Potato Chips 150g','potato-chips-150g','Kettle-cooked sea salt chips.',6.90,5.50,170,'pack','/assets/images/products/potato-chips-150g.jpg','active',1,1),
(5,'Oaty','Chocolate Chip Cookies 300g','choc-chip-cookies-300g','Buttery cookies with dark choc chips.',8.90,NULL,120,'pack','/assets/images/products/choc-chip-cookies-300g.jpg','active',0,0),
(5,'Nutri Farm','Roasted Almonds 200g','roasted-almonds-200g','Dry-roasted almonds, lightly salted.',16.90,14.90,75,'pack','/assets/images/products/roasted-almonds-200g.jpg','active',0,1),
(6,'Frosty','Chicken Nuggets 1kg','chicken-nuggets-1kg','Crispy breaded nuggets, family pack.',21.90,18.90,80,'pack','/assets/images/products/chicken-nuggets-1kg.jpg','active',1,0),
(6,'Gelato Mio','Vanilla Ice Cream 1.5L','vanilla-ice-cream-15l','Madagascar vanilla bean ice cream.',19.50,NULL,60,'tub','/assets/images/products/vanilla-ice-cream-15l.jpg','active',1,1),
(6,'Quick Meal','Frozen Roti Canai 8s','frozen-roti-canai-8s','Flaky frozen roti, ready in minutes.',10.90,9.50,95,'pack','/assets/images/products/frozen-roti-canai-8s.jpg','active',0,1),
(7,'Padi Emas','Jasmine Rice 5kg','jasmine-rice-5kg','Fragrant Thai jasmine rice.',32.90,29.90,70,'bag','/assets/images/products/jasmine-rice-5kg.jpg','active',1,1),
(7,'Saji','Cooking Oil 2kg','cooking-oil-2kg','Cholesterol-free blended cooking oil.',18.50,NULL,110,'bottle','/assets/images/products/cooking-oil-2kg.jpg','active',0,0),
(7,'Nonna','Spaghetti 500g','spaghetti-500g','Durum wheat spaghetti, bronze-cut.',5.90,4.90,150,'pack','/assets/images/products/spaghetti-500g.jpg','active',0,0),
(7,'Rempah Ratus','Chicken Curry Paste 200g','chicken-curry-paste-200g','Authentic Malaysian curry paste.',7.50,NULL,130,'pack','/assets/images/products/chicken-curry-paste-200g.jpg','active',0,0),
(8,'BersihCo','Laundry Detergent 3L','laundry-detergent-3l','Concentrated fresh-scent detergent.',24.90,21.90,60,'bottle','/assets/images/products/laundry-detergent-3l.jpg','active',0,0),
(8,'BersihCo','Kitchen Paper Towels 6 Rolls','kitchen-towels-6rolls','Absorbent 2-ply kitchen towels.',16.50,NULL,90,'pack','/assets/images/products/kitchen-towels-6rolls.jpg','active',0,0),
(9,'Herba','Shampoo 500ml','herbal-shampoo-500ml','Gentle daily shampoo, all hair types.',19.90,16.90,75,'bottle','/assets/images/products/herbal-shampoo-500ml.jpg','active',0,0),
(9,'Herba','Hand Wash Refill 1L','hand-wash-refill-1l','Antibacterial hand wash refill.',12.90,NULL,105,'pack','/assets/images/products/hand-wash-refill-1l.jpg','active',0,0),
(1,'Local Farm','Avocado Hass 2s','avocado-hass-2s','Creamy hass avocados, ready to eat.',13.90,11.90,50,'pack','/assets/images/products/avocado-hass-2s.jpg','active',1,0),
(5,'Oaty','Granola Honey 400g','granola-honey-400g','Baked honey granola clusters.',15.90,NULL,80,'pack','/assets/images/products/granola-honey-400g.jpg','active',0,0);

INSERT INTO coupons (code,type,value,min_subtotal,usage_limit,status,expires_at) VALUES
('FRESH10','percent',10.00,50.00,500,'active','2027-12-31'),
('WELCOME5','fixed',5.00,30.00,1000,'active','2027-12-31');
INSERT INTO products (category_id,brand,name,slug,description,price,discount_price,stock_quantity,unit,image,status,is_featured,is_bestseller) VALUES
(1,'Harumanis Farm','Honey Mangoes 1kg','honey-mangoes-1kg','Sweet juicy harumanis mangoes, tree-ripened.',12.90,10.90,80,'kg','/assets/images/products/honey-mangoes-1kg.jpg','active',1,1),
(1,'Organic Select','Broccoli 500g','broccoli-500g','Tight-floret broccoli, cut this morning.',6.90,NULL,70,'pack','/assets/images/products/broccoli-500g.jpg','active',0,0),
(1,'Local Farm','Carrots 1kg','carrots-1kg','Crunchy orange carrots, great for juicing.',5.50,NULL,120,'kg','/assets/images/products/carrots-1kg.jpg','active',0,0),
(1,'Sunkist','Sunkist Oranges 1kg','sunkist-oranges-1kg','Seedless navel oranges, vitamin C packed.',13.90,11.90,90,'kg','/assets/images/products/sunkist-oranges-1kg.jpg','active',1,0),
(1,'Fresh Daily','Red Grapes 500g','red-grapes-500g','Seedless red grapes, crisp and sweet.',14.90,NULL,75,'pack','/assets/images/products/red-grapes-500g.jpg','active',0,1),
(1,'Johor Farm','MD2 Pineapple 1pc','md2-pineapple-1pc','Super-sweet MD2 pineapple, ready to eat.',8.90,NULL,60,'pc','/assets/images/products/md2-pineapple-1pc.jpg','active',0,0),
(1,'Veggie Box','Potatoes 2kg','potatoes-2kg','All-rounder potatoes for fry, mash or curry.',9.90,NULL,110,'bag','/assets/images/products/potatoes-2kg.jpg','active',0,0),
(1,'Organic Select','Salad Mix 250g','salad-mix-250g','Washed rocket, lettuce and spinach mix.',7.50,NULL,55,'pack','/assets/images/products/salad-mix-250g.jpg','active',1,0),
(1,'Fresh Daily','Lemons 500g','lemons-500g','Zesty lemons for drinks and cooking.',6.90,NULL,85,'pack','/assets/images/products/lemons-500g.jpg','active',0,0),
(1,'Local Farm','Red Onions 1kg','red-onions-1kg','Pungent red onions, sambal essential.',7.90,NULL,130,'kg','/assets/images/products/red-onions-1kg.jpg','active',0,0),
(2,'Farm Fresh','Chicken Breast 500g','chicken-breast-500g','Lean boneless chicken breast, high protein.',14.90,12.90,50,'pack','/assets/images/products/chicken-breast-500g.jpg','active',1,1),
(2,'Premium Beef','Beef Mince 500g','beef-mince-500g','Freshly minced beef, perfect for pasta and burgers.',21.90,NULL,30,'pack','/assets/images/products/beef-mince-500g.jpg','active',0,0),
(2,'Farm Fresh','Chicken Wings 1kg','chicken-wings-1kg','Juicy mid-joint wings, air-fryer favourite.',18.90,16.90,45,'pack','/assets/images/products/chicken-wings-1kg.jpg','active',0,1),
(3,'Golden Churn','Salted Butter 250g','butter-salted-250g','Creamy salted butter for baking and toast.',12.90,NULL,65,'block','/assets/images/products/butter-salted-250g.jpg','active',0,0),
(3,'Formaggio','Mozzarella 250g','mozzarella-250g','Stretchy mozzarella ball for pizza night.',15.90,NULL,40,'pack','/assets/images/products/mozzarella-250g.jpg','active',1,0),
(3,'Dairy Best','Condensed Milk 500g','condensed-milk-500g','Thick creamy condensed milk for teh tarik.',8.90,7.90,100,'can','/assets/images/products/condensed-milk-500g.jpg','active',0,1),
(4,'AquaPure','Mineral Water 6x1.5L','mineral-water-6x15l','Natural mineral water, family carton.',11.90,NULL,140,'pack','/assets/images/products/mineral-water-6x15l.jpg','active',0,0),
(4,'FizzPop','Cola 325ml 4-Pack','cola-325ml-4pack','Classic cola fizz, chilled best.',7.90,NULL,150,'pack','/assets/images/products/cola-325ml-4pack.jpg','active',0,1),
(4,'Tropica','Coconut Water 1L','coconut-water-1l','Pure coconut water, no added sugar.',9.90,NULL,80,'bottle','/assets/images/products/coconut-water-1l.jpg','active',1,0),
(4,'Tropica','Apple Juice 1L','apple-juice-1l','Pressed apple juice, kids favourite.',8.90,NULL,95,'bottle','/assets/images/products/apple-juice-1l.jpg','active',0,0),
(5,'Mamee-Style','Instant Noodles 5-Pack','instant-noodles-5pack','Springy curry-flavoured instant noodles.',6.50,5.50,200,'pack','/assets/images/products/instant-noodles-5pack.jpg','active',1,1),
(5,'Cacao Rich','Dark Chocolate 100g','dark-chocolate-100g','70 percent dark chocolate bar, less sweet.',9.90,NULL,90,'bar','/assets/images/products/dark-chocolate-100g.jpg','active',0,0),
(5,'Nutri Farm','Roasted Peanuts 300g','roasted-peanuts-300g','Crunchy roasted peanuts, classic snack.',7.90,NULL,110,'pack','/assets/images/products/roasted-peanuts-300g.jpg','active',0,0),
(6,'Frosty','Pepperoni Pizza 400g','frozen-pepperoni-pizza','Wood-fired style pepperoni pizza, 12 min oven.',21.90,18.90,45,'box','/assets/images/products/frozen-pepperoni-pizza.jpg','active',1,0),
(6,'Frosty','Shoe-string Fries 1kg','frozen-fries-1kg','Crispy fast-food style fries, air-fry ready.',12.90,10.90,70,'pack','/assets/images/products/frozen-fries-1kg.jpg','active',0,1),
(6,'Gelato Mio','Ice Cream Cones 4s','ice-cream-cones-4s','Mini vanilla-choc cones, kid-size treats.',11.90,NULL,60,'box','/assets/images/products/ice-cream-cones-4s.jpg','active',0,0),
(7,'Cap Sauh','Wheat Flour 1kg','wheat-flour-1kg','All-purpose flour for kuih and baking.',4.90,NULL,160,'pack','/assets/images/products/wheat-flour-1kg.jpg','active',0,0),
(7,'Lebah Asli','Wild Honey 500g','wild-honey-500g','Raw wild honey, thick and fragrant.',24.90,21.90,40,'jar','/assets/images/products/wild-honey-500g.jpg','active',1,0),
(7,'Oaty','Rolled Oats 800g','rolled-oats-800g','Wholegrain rolled oats for breakfast.',11.90,NULL,85,'pack','/assets/images/products/rolled-oats-800g.jpg','active',0,1),
(7,'Rempah Ratus','Chili Flakes 100g','chili-flakes-100g','Spicy dried chili flakes for pizza and pasta.',6.90,NULL,120,'pack','/assets/images/products/chili-flakes-100g.jpg','active',0,0),
(7,'Tomato Gold','Tomato Ketchup 500g','tomato-ketchup-500g','Tangy tomato ketchup, fry companion.',7.90,6.90,130,'bottle','/assets/images/products/tomato-ketchup-500g.jpg','active',0,0),
(7,'Nelayan','Canned Sardines 425g','canned-sardines-425g','Sardines in tomato sauce, pantry hero.',9.90,NULL,105,'can','/assets/images/products/canned-sardines-425g.jpg','active',0,0),
(8,'BersihCo','Floor Cleaner 2L','floor-cleaner-2l','Lemongrass floor cleaner, kills 99 percent germs.',13.90,11.90,55,'bottle','/assets/images/products/floor-cleaner-2l.jpg','active',0,0),
(8,'BersihCo','Multipurpose Spray 500ml','multipurpose-spray-500ml','Grease-cutting spray for kitchen and table.',9.90,NULL,75,'bottle','/assets/images/products/multipurpose-spray-500ml.jpg','active',0,0),
(9,'Herba','Body Lotion 400ml','body-lotion-400ml','Moisturising body lotion with aloe.',24.90,21.90,50,'bottle','/assets/images/products/body-lotion-400ml.jpg','active',0,0),
(9,'Herba','Creamy Body Wash 800ml','body-wash-800ml','Gentle creamy body wash, family size.',18.90,NULL,70,'bottle','/assets/images/products/body-wash-800ml.jpg','active',0,0);
