<h1><?= e(t('My account')) ?></h1>
<div class="card"><h3>★ <?= e(t('Loyalty points:')) ?> <?= number_format((int)($u['points'] ?? 0)) ?></h3><p class="muted">Belanja RM 1 = 1 mata · 100 mata = RM 1 diskaun di checkout.</p></div>
<div class="agrid">
<div class="card"><h3><?= e(t('Profile photo')) ?></h3>
<div class="avarow"><?php if (!empty($u['avatar'])): ?><img class="avatar lg" src="<?= e($u['avatar']) ?>" alt="Profile photo"><?php endif; ?>
<form method="post" action="/account/avatar" enctype="multipart/form-data" class="row"><?= csrf_field() ?><input type="file" name="avatar" accept="image/jpeg,image/png,image/webp" required><button class="btn"><?= e(t('Upload')) ?></button></form></div>
<h3><?= e(t('Profile')) ?></h3><form method="post" action="/account/profile"><?= csrf_field() ?><label><?= e(t('Name')) ?><input name="name" value="<?= e($u['name']) ?>"></label><label><?= e(t('Phone')) ?><input name="phone" value="<?= e($u['phone'] ?? '') ?>" inputmode="tel"></label><button class="btn"><?= e(t('Update')) ?></button></form>
<h3><?= e(t('Security')) ?></h3><form method="post" action="/account/password"><?= csrf_field() ?><label><?= e(t('Current')) ?><input name="current" type="password" autocomplete="current-password"></label><label><?= e(t('New (8+)')) ?><input name="new" type="password" minlength="8" autocomplete="new-password"></label><button class="btn"><?= e(t('Change password')) ?></button></form></div>
<div class="card"><h3><?= e(t('Addresses')) ?></h3><?php foreach ($addrs as $a): ?><div class="srow"><span><?= e($a['label']) ?> — <?= e($a['line1']) ?>, <?= e($a['city']) ?></span><form method="post" action="/account/address/<?= (int)$a['id'] ?>/delete"><?= csrf_field() ?><button class="link"><?= e(t('Delete')) ?></button></form></div><?php endforeach; ?>
<form method="post" action="/account/address"><?= csrf_field() ?><div class="row"><label><?= e(t('Label')) ?><input name="label" value="Home"></label><label><?= e(t('Recipient')) ?><input name="recipient" required></label></div><div class="row"><label><?= e(t('Phone')) ?><input name="phone" required inputmode="tel"></label><label><?= e(t('Street')) ?><input name="line1" required></label></div><div class="row"><label><?= e(t('City')) ?><input name="city" required></label><label><?= e(t('Postcode')) ?><input name="postcode" required inputmode="numeric"></label></div><button class="btn"><?= e(t('Save address')) ?></button></form></div>
</div>
<div class="agrid"><div class="card"><h3><?= e(t('Recent orders')) ?></h3><?php if (!$orders): ?><p class="muted"><?= e(t('No orders yet.')) ?></p><?php endif; ?><?php foreach ($orders as $o): ?><div class="srow"><a href="/orders/<?= (int)$o['id'] ?>"><?= e($o['order_number']) ?></a><b><?= money((float)$o['total']) ?></b></div><?php endforeach; ?><a href="/orders"><?= e(t('View all →')) ?></a></div>
<div class="card"><h3><?= e(t('Wishlist')) ?></h3><?php if (!$wl): ?><p class="muted"><?= e(t('Nothing saved yet.')) ?></p><?php endif; ?><?php foreach ($wl as $w): ?><div class="srow"><a href="/product/<?= e($w['slug']) ?>"><?= e($w['name']) ?></a><b><?= money((float)($w['discount_price'] ?? $w['price'])) ?></b></div><?php endforeach; ?></div></div>
